language: node_js

node_js:
  - '8'

cache:
  directories:
    - $HOME/.npm
    - node_modules
    - .eslintcache

before_install:
  - dpkg --compare-versions `npm -v` ge 6.0 || npm i -g npm@latest

install:
  - if [[ "$TRAVIS_BRANCH" = "greenkeeper/"* ]]; then npm install; else npm ci; fi

before_script:
  - greenkeeper-lockfile-update

script:
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - greenkeeper-lockfile-upload
